CREATE TABLE IF NOT EXISTS pagamenti (
  id SERIAL PRIMARY KEY,
  prenotazione_id INTEGER REFERENCES prenotazioni(id),
  "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  metodo VARCHAR(50) NOT NULL,
  importo DECIMAL(10,2) NOT NULL
);
